version: '3'

services:

  spring-boot-admin:
    image: matheuscarv69/spring-boot-admin-server
    container_name: spring_boot_admin
    environment:
      SERVER_PORT: 8081
    ports:
      - "8081:8081"

  postgres:
    image: 'postgres:alpine'
    container_name: postgres_pegasus
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
