version: '3'

services:
  postgres:
    image: 'postgres:alpine'
    container_name: postgres_pegasus
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
