global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'pegasus-rent-a-car'
    scrape_interval: 5s
    metrics_path: '/pegasus/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] # api server